### ISSUE TITLE
position of stamina bar

### ISSUE THREAD

**Issue by MoNTE48** [minetest-mods/stamina#1]
This is a great idea and make it easier to rewrite a very hard hud and hunger.
But I see some issues.
I believe that we should stick to the location of the bars Minecraft:
armor air 
health hunger
Let me explain why. When we see this:
hunger
health
we occupied all the space on the left, but a lot of free space on the right. We really rarely swim under water. Just display Armor
hunger armor
healt
In my opinion it is not aesthetically pleasing, and stupid. Armour is directly related to health, they need to be one below the other. Do not diagonally.

**Comment by sofar** [comment]
Noted.

**Comment by sofar** [comment]
I'm going to close this feature request. But I'd like to explain why I"m not currently considering this in detail.

I didn't set out to replace the `hunger`+`hud` mods when I assembled this code. I also do not intend to maintain a hostile fork of these 2 mods, so, for the purposes of this mod, if people request changes that make it work more like the original mods, then I'd like to ask that they please consider using those two mods together instead.

Second, for the technical argument, I do not want to start juggling the internal statbars. This is out of scope of what I want to achieve with this code. To explain more in-depth: the builtin breath statbar would need to be moved in order to do what you want. The code needed to do this would force me to re-implement large parts of what `hud` does. I want to keep the code small, and focus on the gameplay effects, not on the cosmetics.

You have the option of forking this mod, attempting to convince me with patches[1], or work with @blockment on improving his version to suit your needs. But this issue is closed unless [1].

**Comment by MoNTE48** [comment]
Good. This mode can be used in conjunction with HUD (instead of hunger)?
